version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000" # Frontend port
      - "4000:4000" # Backend port
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_PORT=4000
      - NEXT_PUBLIC_SOCKET_SERVER_URL="https://online-chess-production.up.railway.app:4000"
